version: "3"

services:
  dev.php-fpm.srv:
    image: php:7.2.6
    build: ./
    volumes:
      - ./etc:/home/work/app/php/etc
      - ./extensions:/home/work/app/php/lib/php/extensions/no-debug-non-zts-20170718
      - ../logs/phpfpm:/home/work/logs
      - ../../code/www:/home/work/www
    ports:
      - "9000:9000"
    #restart: always
    privileged: true
    networks:
      - default
networks:
  default:
    external:
      name: dockerenv_default
