version: "3"

services:
  php-fpm:
    image: lei_php:7.2.6
    build: ./
    volumes:
      - ./etc:/home/work/app/php/etc
      - ../www:/home/work/www
    ports:
      - "9000:9000"
    restart: always
    networks:
      - default
networks:
  default:
    external:
      name: dockerenv_default
